# remap prefix from 'Ctrl-b' to 'Ctrl-a'
set-option -g prefix C-a
# Free up Ctrl+b
unbind C-b
# Allow Ctrl+a to work with apps in tmux (do it twice)
bind-key C-a send-prefix


set -g status-keys vi
# Set window index to start at 1
setw -g base-index 1
# and the pane index too
setw -g pane-base-index 1
# Bind prefix r to reload this config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Mouse config
set-option -g mouse on
set -g mouse on
setw -g mouse on

set -g history-limit 4000

# Enter copy-mode to allow mouse-scroll
# Does not exit though!
bind -n WheelUpPane copy-mode

# Shift arrow to switch windows
# bind -n j  previous-window
# bind -n k next-window
